package pl.zdusza.event;

public enum LoggableEventName {
    INVALID_MONITORING_EVENT,
    AUTH_FAILED,
    UNHANDLED_VERTX_EXCEPTION, UNHANDLED_ROUTER_EXCEPTION,
    RESPONSE_TIME, HIGH_RESPONSE_TIME,
    WORKER_SUCCEDED, WORKER_FAILED,
    HEALTH_CHECK_SUCCEDED, HEALTH_CHECK_FAILED
}
