package pl.zdusza.event;

public enum StorableEventName {
    PAGE_LOADED, SESSION_EXPIRED, USER_LOGGED_IN, USER_NOT_LOGGED_IN, USER_LOGGED_OUT, USER_REGISTERED,
    USER_NOT_REGISTERED, USER_ACTIVATED, USER_NOT_ACTIVATED_BECAUSE_USER_NOT_REGISTERED,
    USER_NOT_ACTIVATED_BECAUSE_LINK_EXPIRED
}
