package pl.zdusza.event;

public enum StorableEventName {
    // ALL
    PAGE_LOADED, SESSION_EXPIRED, USER_LOGGED_OUT,
    // ACCOUNT
    USER_LOGGED_IN, USER_NOT_LOGGED_IN,
    USER_REGISTERED, USER_NOT_REGISTERED,
    USER_ACTIVATED, USER_NOT_ACTIVATED,
    RESET_LINK_CREATED, RESET_LINK_NOT_CREATED,
    RESET_PASSWORD_CHANGED, RESET_PASSWORD_NOT_CHANGED,

    // ENGLISH
    LESSON_STARTED, EXCERCISES_STARTED, EXCERCISES_FINISHED, LESSON_FINISHED,

    FIRST_EXC_CORRECT, FIRST_EXC_INCORRECT, SECOND_EXC_CORRECT, SECOND_EXC_INCORRECT,
    THIRD_EXC_CORRECT, THIRD_EXC_INCORRECT, FOURTH_EXC_CORRECT, FOURTH_EXC_INCORRECT,
    FIFTH_EXC_CORRECT, FIFTH_EXC_INCORRECT, SIXTH_EXC_CORRECT, SIXTH_EXC_INCORRECT,

    FIRST_REP_CORRECT, FIRST_REP_INCORRECT, SECOND_REP_CORRECT, SECOND_REP_INCORRECT,
    THIRD_REP_CORRECT, THIRD_REP_INCORRECT, FOURTH_REP_CORRECT, FOURTH_REP_INCORRECT,
    FIFTH_REP_CORRECT, FIFTH_REP_INCORRECT, SIXTH_REP_CORRECT, SIXTH_REP_INCORRECT,
}
